### ISSUE TITLE
使用时出现UnsatisfiedLinkError异常

### ISSUE THREAD

**Issue by Lee-swifter** [geek5nan/AndroidMuPDFDemo#1]
按照README使用后出现这个问题:
```
    java.lang.UnsatisfiedLinkError: Couldn't load mupdf from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mupd.example-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mupd.example-1, /vendor/lib, /system/lib]]]: findLibrary returned null
    at java.lang.Runtime.loadLibrary(Runtime.java:358)
    at java.lang.System.loadLibrary(System.java:526)
    at com.artifex.mupdfdemo.MuPDFCore.<clinit>(MuPDFCore.java:14)
    at com.mupd.example.activity.PDFReaderActivity.openFile(PDFReaderActivity.java:85)
    at com.mupd.example.activity.PDFReaderActivity.onCreate(PDFReaderActivity.java:47)
    at android.app.Activity.performCreate(Activity.java:5246)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1089)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
    at android.app.ActivityThread.access$800(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5085)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at dalvik.system.NativeStart.main(Native Method)
```
so文件也引入了。
另外，引入了这个依赖库后自己的应用名会变成**MuPDF**。

**Comment by geek5nan** [comment]
最近刚进入工作状态,不好意思啊~
上边说的两个问题
`Couldn't load mupdf`
这个是在模拟器运行时出现的异常吗,如果是的话可能是项目中没有添加x86相关so文件导致.
`引入后应用名称变为MuPDF`
这个可以删除mupdf模块中的res/string相关配置来修复.

MuPDF挺好用的,我在用事也进了不少坑,你再看看,有问题的话再来咨询我.
